Vagrant.configure("2") do |config|
  # for unix use "/dev/sr0" or something like that
  # for windows use "D:" or something like that
  optical_drive = "/dev/sr0"

  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.provision :shell, :path => "Vagrantfile-bootstrap.sh"
  config.vm.synced_folder "rip/", "/var/rip"

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "4096"]
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "0", "--device", "0", "--type", "dvddrive", "--medium", "Host:" + optical_drive, "--passthrough", "on"]
  end
end
